# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
#whitelist branches
branches:
  only:
    - master

language: R
sudo: false
cache: packages

warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

notifications:
    slack: googleauthrverse:tGfXjSD58cQSEr1YuzQ5hKPS

after_success:
  - Rscript -e 'covr::codecov()'
